### ISSUE TITLE
[Jupiter] Create indexing functionality to ERA Thesis "Department" and "Supervisor" fields

### ISSUE THREAD

**Issue by ERAHelp** [ualbertalib/jupiter#1002]
Being able to search for UA theses by the Department granting the degree and the Supervisor(s) who supervised the thesis has been repeatedly requested by our users over the years, and will add a lot of usability to our records (this a a popular search field in other Thesis databases such as Proquest Dissertation Abstracts).

Leah has stated that she would like this functionality added during the next Sprint if possible, with the understanding from prior discussion that it may be a fairly easily added feature.

Anna

**Comment by weiweishi** [comment]
As discussed with @abombak These fields are currently indexed, and items can be located with an exact search. Issues are with the inconsistency of the data in these fields. 
What can be done:
- make the text a phrase search link on the record view, to find items with exact matched supervisor/department names

What needs to be discussed:
- Can we add facets when searching within Thesis Collection, allowing people to find variations of names of the same departments etc?
- Can metadata team create a report, of the various department names used. 

Note this function is for advanced users only - can we allow search within certain fields with a search syntax to define the search scope?

**Comment by anayram** [comment]
@ERAHelp and @weiweishi - will create a report and share.

**Comment by anayram** [comment]
reports from solr production. thanks, @danydvd !
https://drive.google.com/file/d/1MKJ6XIQWrPLximtvuadmr-ejC12WFxbz/view?usp=sharing
https://drive.google.com/file/d/1IDcITmR6C2z7E4V-abmRJVSAS3nUux8-/view?usp=sharing

**Comment by pgwillia** [comment]
For example with department:
https://github.com/ualbertalib/jupiter/blob/e797c4f9961bff205e5482c190f884102db9a6c2/app/views/items/_thesis_more_information.html.erb#L45-L58
and this would generate the link: `search_link_for(@item, :departments, facet: :search, value: department)`

**Comment by weiweishi** [comment]
Based on a conversation with @abombak, adding the search links for Department and Supervisor addresses the pressing need. It would still be good to consider adding Department facet specifically for the theses collection. But this would be a nice-to-have feature.

**Comment by weiweishi** [comment]
Notice it says department_tesim on the UI, could we improve this display, instead of using the solr field name, use the display label "Department"?
<img width="846" alt="Screen Shot 2019-03-11 at 11 15 36 PM" src="https://user-images.githubusercontent.com/2047614/54176243-b586de80-4453-11e9-8b76-29a16adeeaf7.png">

**Comment by pgwillia** [comment]
The way this is handled for other attributes is with 'facet' behaviour.  We could make these 'facets' and reindex. (See https://github.com/ualbertalib/jupiter/pull/1060)

Is there any appetite for an advanced search like behaviour?  Right now the search created for the link is just executed exactly as is with the solr field flowing all the way through.  I was thinking of adding logic to interpret/validate `http://localhost:3000/search?search[supervisors_sim][]=Frank+N.+Sense+(Administration)` instead of `http://localhost:3000/search?search=supervisors_tesim%3A%22Frank+N.+Sense+%28Administration%29%22`

**Comment by weiweishi** [comment]
@pgwillia 
confirmed with @leahvanderjagt and @abombak that they'd like to add both of them as facets. Would you mind finishing up this work?
