### ISSUE TITLE
DOI Port from Hydranorth

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#103]
DONE WHEN

- [x] AASM working w/ Rails 5.1, latest ActiveFedora
- [x] AASM-based DOI lifecycle callbacks working in Jupiter
- [x] Tests ported

**Comment by mbarnett** [comment]
Initial port working in https://github.com/ualbertalib/jupiter/tree/doi

**Comment by mbarnett** [comment]
(Needs a significant merge to be brought up to date with master, right now)

**Comment by sfarnel** [comment]
Jupiter [DOI registration mapping](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/Jupiter%20DOI%20registration%20mapping%20(EZID).md) for EZID.

On transition to DataCite as our OAI provider the element terms and syntax in the API call will be different, but the content should remain the same, because it reflects mandatory elements in the DataCite schema (4.1)

**Comment by pbinkley** [comment]
NB Datacite now provides an EZID-compatible API (called "EZ API"). To test it we need to email them to get access. When we return to this ticket post-beta let's do that.

**Comment by mbarnett** [comment]
I'm going to call this "done" and we can probably open a new ticket to track transitioning to Datacite's compatibility API?
