### ISSUE TITLE
Problem with Medical Laboratory Image batch ingest - no thumbnails

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#1175]
**Describe the bug**
It seems that most of the tiff images that were batch ingested did not have a thumbnail generated on ingest. On desktop these download even when you click view.

**To Reproduce**
1. Go to https://doi.org/10.7939/R3GX45891 (for example) 
2. You'll see no thumbnail image
3. Click on View
4. The file will download rather than open in the browser (although the researcher showed me it works on his tablet) 

Item should have a thumbnail image and should allow the user to view not just download.

On Windows, using Chrome

The researcher is eagerly awaiting these fixes so he can showcase the collection and the service (which he is super excited about).

**Comment by ConnorSheremeta** [comment]
The missing thumbnail image issue for '.tifs' was previously reported [here](https://github.com/ualbertalib/jupiter/issues/991). I did some digging and added a comment to that issue.

**Comment by ConnorSheremeta** [comment]
As for viewing tif images, [chrome does not support this as of right now](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support) and there's no indication that they ever will.

**Comment by weiweishi** [comment]
@sfarnel see the sidenote on the page referred by @ConnorSheremeta:
_Although it [tiff] was one of the first suggested WWW image formats, most browsers support TIFF by using a plugin installed by the user instead of decoding it natively._

Tested on Chrome and FF on my desktop and both downloaded the file. But on my mac with Safari and Chrome, as well as Safari on my phone, it opens the images on a separate tab. There are browser extensions that are built to view tiff files in the browser if that is desired.

**Comment by sfarnel** [comment]
Thanks @weiweishi Indeed, not much we can do about those browsers :)

**Comment by weiweishi** [comment]
Closing this now as we've fixed the thumbnail issue in production
