### ISSUE TITLE
Problem with Medical Laboratory Image batch ingest - all keywords lumped into one big block

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/jupiter#1177]
**Describe the bug**
Some of the batch ingested items have all of the subject terms in one single block.

**To Reproduce**
1. Go to one of the affected items (https://doi.org/10.7939/R3WH2DW6C)
2. See all subjects/keywords in one big long string rather than listed individually

**Expected behavior**
They should appear as individual keywords.

Individual keywords:
![image](https://user-images.githubusercontent.com/4697932/59938520-76810580-9412-11e9-962b-511d3a17b11c.png)

All keywords in one long string:
![image](https://user-images.githubusercontent.com/4697932/59938556-8e588980-9412-11e9-8479-bdc33fa3cb8f.png)

Windows using Chrome

The researcher is eagerly awaiting these fixes so he can showcase the collection and the service (which he is super excited about).

**Comment by weiweishi** [comment]
@sfarnel this is not a bug of the application. I will fix the data on the batch, but some improvement on the batch ingest data is needed - subjects should be separated with "|" instead of ",", as well as any other multi-value fields, in order for them to be ingested individually. I wonder where would be the best place to capture this as a note on the batch ingest - maybe I will add this as a comment/note on the batch ingest template?

**Comment by sfarnel** [comment]
Thanks @weiweishi indeed, this was a problem with the data on ingest, as well as a combination of individual item input along with ingest by batch. Reminds us of the need for review prior to ingest

**Comment by weiweishi** [comment]
@sfarnel @leahvanderjagt data has been cleaned.
