### ISSUE TITLE
[Spike] investigate UI/SOLR for using "OR" instead of "AND"

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#1261]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to be able to select multiple options in the author facet category, and 
 I would like the search logic to be "OR", so I can select same author with the variation (Jane Doe or J. Doe or Jane M. Doe etc)
Similarly with the department facet - Work done here #1060 

- [ ] Initial investigation on UI options, and Solr configuration that would enable the use of "OR" instead of "AND"

**Comment by pgwillia** [comment]
New egg experience
![Screenshot from 2019-10-18 15-35-56](https://user-images.githubusercontent.com/1220762/67129875-00708d80-f1bd-11e9-9164-707f8b4e6640.png)
![Screenshot from 2019-10-18 15-35-45](https://user-images.githubusercontent.com/1220762/67129876-00708d80-f1bd-11e9-8cdc-78d5c884bdab.png)
![Screenshot from 2019-10-18 15-35-33](https://user-images.githubusercontent.com/1220762/67129877-00708d80-f1bd-11e9-8535-675113c70e48.png)

**Comment by pgwillia** [comment]
From https://articles.uie.com/faceted_search2part2/
>  Multiple Selection from a Facet

> The most common use case for faceted search or navigation is to select at most one value per facet, but there are at least two ways from which a user might select multiple values from the same facet:

>  Disjunctive (OR) selection. Selecting a range (e.g., a price or date range) may be a kind of disjunctive selection, depending how the values are represented.
>  Conjunctive (AND) selection.

> The design challenge is to communicate to users whether selecting multiple values from a particular facet is disjunctive or conjunctive—particularly if the site offers both behaviors. Users are notoriously bad at inferring Boolean logic from subtle cues.

> It is important to use an interface that not only is self-consistent but also adheres to familiar conventions. For example, the check boxes in Figure 7.6 adheres to the convention for disjunctive selection.
results in Help
Figure 7.6: Results for “ribs” in New York at www.yelp.com.
![yelp](https://user-images.githubusercontent.com/1220762/67312191-24361b00-f4be-11e9-9fe1-213779f446a8.jpg)

> There are fewer interfaces that allow conjunctive selection from the same facet, but a convention for those that do is to present the selections as ordinary links, as with the topic facet in Figure 7.7.
results in fcla
Figure 7.7: Results for “tax law” at www.fcla.edu.
![fllibraries](https://user-images.githubusercontent.com/1220762/67312212-2ef0b000-f4be-11e9-8f9e-c4d49722624d.jpg)

> The approach may make the user think that he or she is drilling down a hierarchy, but fortunately that misinterpretation is consistent with the narrowing effect of conjunctive selection.

> Perhaps most importantly, we urge caution in combing disjunctive and conjunctive selection in the same interface. Users who can understand such a complex process will be better served by the ability to construct Boolean queries at a command line.

> A rule of thumb is that facets that are typically singly assigned to documents (e.g., brand, document type) work well with disjunctive selection, whereas facets that are often multiply assigned to documents (e.g., consumer electronics features, topic) work well with conjunctive selection.

**Comment by pgwillia** [comment]
Example from Crate & Barrel

This is the style that would work if there wasn't a lot of options within a filter category.

Menu for categories/taxonomy
![Screenshot from 2019-10-22 12-35-54](https://user-images.githubusercontent.com/1220762/67318465-be02c580-f4c8-11e9-8736-8b50be819441.png)

Filters are ANDed together 
![Screenshot from 2019-10-22 12-33-58](https://user-images.githubusercontent.com/1220762/67318477-c3f8a680-f4c8-11e9-9057-8db08ce96de1.png)
Can choose criteria which are ORed together
![Screenshot from 2019-10-22 12-34-23](https://user-images.githubusercontent.com/1220762/67318476-c3f8a680-f4c8-11e9-9adf-ad0d8361ea4a.png)

**Comment by pgwillia** [comment]
Atlassian Jira deals with filters that have a lot of content.
![Screenshot from 2019-10-22 12-41-48](https://user-images.githubusercontent.com/1220762/67319028-97915a00-f4c9-11e9-9780-483744b5bcc5.png)
![Screenshot from 2019-10-22 12-41-36](https://user-images.githubusercontent.com/1220762/67319029-97915a00-f4c9-11e9-8796-51db797ebdef.png)

You can select multiple options that seem to OR values together.

**Comment by pgwillia** [comment]
From https://baymard.com/blog/horizontal-filtering-sorting-design
> In short: our usability study showed that a horizontal filtering and sorting toolbar is only appropriate for certain types of e-commerce sites – yet for those sites, it can significantly outperform the traditional left-hand filtering sidebar.

> it only works well for industries and site types that naturally have few filters. 

> Specifically, make sure that:
> - Filtering values are implemented as a custom drop-down interface, that
> - Allow multiple filtering values of the same type to be selected,
> - Auto-apply and live-update the product list as each value is clicked, and
> - Display any applied filtering values outside the drop-down.

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/jupiter/blob/26c362419e99ed9e4b927ba75f1c1cafb3865dd5/app/models/jupiter_core/search.rb#L40-L42
https://github.com/ualbertalib/jupiter/blob/26c362419e99ed9e4b927ba75f1c1cafb3865dd5/app/models/jupiter_core/search.rb#L51

https://lucene.apache.org/solr/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-BooleanOperatorsSupportedbytheStandardQueryParser

The OR operator is the default conjunction operator. This means that if there is no Boolean operator between two terms, the OR operator is used. The OR operator links two terms and finds a matching document if either of the terms exist in a document. This is equivalent to a union using sets. The symbol || can be used in place of the word OR.

To search for documents that contain either "jakarta apache" or just "jakarta," use the query:

`"jakarta apache" jakarta`

or

`"jakarta apache" OR jakarta`

**Comment by pgwillia** [comment]
Bread crumbs could group filter category values with a common background and border, but seperate values to remove individually.
![Screenshot from 2019-10-22 15-15-31](https://user-images.githubusercontent.com/1220762/67334048-cebe3600-f4de-11e9-911f-7afb8731a7bc.png)

There are a lot of considerations for facet navigation.

- side panel vs top
- show all options always vs show currently displayed + show all reveal button
- each click updates the results vs select + apply to update
- mixing AND (radio button) & OR (checkbox) vs uniform experience where all facets behave the same

**Comment by weiweishi** [comment]
Dev team is going to review the options and adding comments to the tickets re: recommended solutions.

**Comment by weiweishi** [comment]
@murny will chime in on the UI design based on @pgwillia's initial investigation

**Comment by murny** [comment]
### Original Goal

> As a user, I would like to be able to select multiple options in the author facet category, and
> I would like the search logic to be "OR", so I can select same author with the variation (Jane Doe or J. Doe or Jane M. Doe etc)

>  Initial investigation on UI options, and Solr configuration that would enable the use of "OR" instead of "AND"

### What we currently have

![image](https://user-images.githubusercontent.com/1930474/72772746-04e48200-3bc2-11ea-82ed-f42c6e1ea53a.png)

- Search results are shown, with facets on left side column. 
- Can click on any "checkbox"  (checkbox in quotes as its actually a link styled with fontawesome to appear like a checkbox) to narrow search results by Facet selection. Similar with limiting by Year, you can hit the "Limit" button. 
- Once facet item clicked, we sent a get request to backend and reload a fresh page
- Fresh page has search results narrowed by facet item. Facets on side left panel have been rearranged, where selected facet is now first facet shown in list. For the selected facet it only shows the one selected item within facet which is now showing as a checked checkbox. Finally above the search results a "selected filter" button showing currently applied facets is shown.  Clicking on this button removes the selected filter and refreshes the page showing the results without this facet being applied.
![image](https://user-images.githubusercontent.com/1930474/72772992-e9c64200-3bc2-11ea-93e8-8340e97c9f5c.png)
Same events happen above on mobile, only instead of a left sidebar, we have a "Filter results" button which pulls out a side tray:
![image](https://user-images.githubusercontent.com/1930474/72773066-272acf80-3bc3-11ea-9692-46f958ce5d03.png)
![image](https://user-images.githubusercontent.com/1930474/72773047-1c703a80-3bc3-11ea-9902-3e848326e81e.png)

### Simplest solution to achieve what we want
 Ultimately we simply just want to be able to select multiple items within the SAME facet. When we do this, these items will be applied as an "OR" query in SOLR.

How to achieve this? Let's use the Author Facet in our example here. 
  - After clicking on a author, "Jane A. Doe" in the author facet, we need to render all the authors in the author facet and make them clickable again. We currently only showing the selected "Jane A. Doe" and hiding the rest. 
- When clicking on an additional author, say "Stephen A. Smith", we need update the results by "OR"ing these two authors together, while "AND"ing any other facets that have been applied. We will need to append "Stephen A. Smith" to the URL as an additional author facet. 
    - Rails has a way to make these query params show up as an Array in the controller, which I'd recommend following. Which looks like we are already doing? For example the query param would like this in ERA: `facets[all_contributors_sim][]: Chopoidalo, Cindy` which means by adding another author to it, `facets[all_contributors_sim][]: Jane, Doe` we get an array back such as `params[:facets][:all_contributors_sim] => ["Chopoidalo, Cindy", "Jane, Doe"]`. This should make things much easier for ourselves
    - We will most likely need to do some work here in the backend, such as `jupiter/app/models/jupiter_core/search.rb` as Trica mentioned above. We need to take this array and apply "OR" between each item within the array.
- Results get updated accordingly by applied facet items. Facets items being applied need to be shown in left side panel accordingly. Applied facet buttons need to be updated to show multiple OR facet items.


Basically above is really not much different then how we currently doing "Subject / Keyword" with the exception that these are being applied as "AND" instead of "OR".

From the UI point of view though they are doing exactly what we want:
![image](https://user-images.githubusercontent.com/1930474/72775086-4c6f0c00-3bca-11ea-8aa7-2ca72485a919.png)
and query params are coming in as an Array:
![image](https://user-images.githubusercontent.com/1930474/72775196-ad96df80-3bca-11ea-8e1a-da00127057f8.png)
We can select multiple of them within the same facet, however since they are being "AND", each item you select reduces the number of items and their counts. It should work like Newegg, where counts remain constant unless your "AND"ing with another facet.

### Possible Enhancements
  - Applied Filters could show more information. Such as the facet they belong to, and if we "OR"ing this could be shown as well nicely. Newegg does a good job here:
Below you have no idea what these applied filters correspond to what facets:
![image](https://user-images.githubusercontent.com/1930474/72774525-2cd6e400-3bc8-11ea-8090-5460a2cb39d1.png)
But Newegg makes this very easy to understand:
![image](https://user-images.githubusercontent.com/1930474/72774578-555ede00-3bc8-11ea-83e5-d99dd7c53549.png)
"Reset" button is also a nice touch to reset all filters

- It might make it easier if the facets were a real form, with real checkboxes instead of links and fontawesome checkbox icons? Might clean up quite a bit of logic within our view helpers, etc. This also applies to the "Sort by" dropdown which is just a dropdown of links. Would give a UX more like other big ecommerce sites linked above which is what users are more familiar with.

- Really like Neweggs solution to this problem, lots of ideas we could potentially borrow from them. Another one is any Shopify site (Staples.ca comes to mind) since its based on Ruby on Rails. 

- Tricia added a lot of interesting articles/ideas above with regards to different solutions for mobile (sliding tray vs full page modal, etc), top horizontal facets vs sidebar vertical facets, and many more examples. All of these could be explored in more detail and experimented with.

###  Possible Concern
- With users able to OR as many items within a facet, this could result in very large URLS. For example simply selecting every Subject/Keyword and every facet I could from the above example, I got my URL to about 1020 characters:
![image](https://user-images.githubusercontent.com/1930474/72775497-d370b400-3bcb-11ea-81eb-3ae43bb269ad.png)
With the added ability to OR facets, this could result in very large URLS. It sounds like chrome has a soft limit of 2048 characters (2 MB) for their URL Length. Looks like a few ecommerce sites will compress their URLs somehow (Amazon, Newegg, etc). Others will limit the number of items in a facet being applied (Best Buy only allows 2 items within a facet to be applied at a time).
- This point sounds like its mute.  As Shopify works exactly like the way we are doing it. On a Shopify website (Staples.ca for example), I easily got my URL length over 3500 characters by applying every facet I could and everything still worked just fine 🤔.
