### ISSUE TITLE
ERA inconsistency when searching for theses

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1488]
Submitted via email from:Era.Helpdesk@ualberta.ca

Devs,

Bug #2!

When searching for theses by the Department Name facet, we are getting
different totals results (this seems to be a new thing, I believe it worked
correctly before).

Using the example of "Department of Earth and Atmospheric Sciences" (the
bug may be related to this Dept only, I haven't checked any others) to
search within the Thesis collection:

departments_tesim:"Earth and Atmospheric" gets a search result of ~421

whereas clicking on the Department of Earth and Atmospheric Sciences facet
in the LH column displays as 91 (+ 1 rogue "E&AS" one)

Anna
ERA Help

--

**Comment by mbarnett** [comment]
This should be fixed, right Connor?

**Comment by mbarnett** [comment]
@ConnorSheremeta just pinging you to look at this if you have a sec next week or early Jan, and close if we've addressed it

**Comment by ConnorSheremeta** [comment]
My apologies, I somehow didn't see these messages. It looks to be addressed from the fedora migration.

https://era.library.ualberta.ca/communities/db9a4e71-f809-4385-a274-048f28eb6814/collections/f42f3da6-00c3-4581-b785-63725c33c7ce?search=departments_tesim%3A%22Earth+and+Atmospheric%22+
returns 461 results (used to be 421)

https://era.library.ualberta.ca/search?facets%5Bdepartments_sim%5D%5B%5D=Department+of+Earth+and+Atmospheric+Sciences&facets%5Bmember_of_paths_dpsim%5D%5B%5D=db9a4e71-f809-4385-a274-048f28eb6814
returns 457 results (used to be 91)

This discrepancy is most likely due to 4 additional deposits since the fedora migration. The only way to know for sure is by doing a re-index and checking right after but I'm not sure that is necessary here, thoughts @mbarnett?
