### ISSUE TITLE
Is Sort By Date working correctly?

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#1731]
This came in from Public Services via OTRS: https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=57570

**Describe the bug**

It looks like sorting search results by date is given results in an unintuitive order.

**To Reproduce**
1. Go to https://era.library.ualberta.ca/communities/b41cdbfd-6af2-4a13-8ba6-59725565d445/collections/06f37b3f-64b5-40d7-aeff-ce4d6855f7cf?direction=desc&sort=sort_year
2. Notice the ordering seems pretty wacky versus the titles and dates displayed.

At a glance, these results look wildly out of order, but that may just be due to them having been added in some kind of weird order that doesn't match their names? Needs investigation to figure out if this is actually an issue, and if so, what is causing it.

**Comment by murny** [comment]
If I recall Date sort is not by Date Created (record_created_at field), its actually sorting by the "sort_year" field (which is typically 4 digit "year" generated off "created" field). So this might explain the weirdness 🤔

**Comment by mbarnett** [comment]
Ok, dug into this a bit:

Yeah, we're setting a [sort here](https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/services/user_search_service.rb#L36), which for "Date (newest first)" is the value `:sort_year`.  Which eventually gets mapped to a solr index and [set as a criteria on the Solr search here](https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/models/jupiter_core/solr_services/deferred_faceted_solr_query.rb#L49).

Problem being that we're sorting on the sort year but we're not at any point handling the fact that there needs to be a 'tie-breaker' for recency on sort year because it's so chunky (hundreds of items will share any given sort year).

I wouldn't want to special case this in the faceted search implementation itself, so my thinking is that we should probably:

1) extend the behaviour of [`DeferredFacetedSolrQuery#sort`](https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/models/jupiter_core/solr_services/deferred_faceted_solr_query.rb#L35) to detect if `attr` is passed as an array, map all the symbols in the array to the corresponding solr indexes, and set the sort clause up as an array of those indexes (it looks like the `sort_clause`, which maps the sort index(es) into the query syntax, [is set up to handle this already](https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/models/jupiter_core/solr_services/deferred_faceted_solr_query.rb#L187))

2) Either at the controller level or in `UserSearchService` (probably the latter) we special-case the handling of when the `:sort` param is `:sort_year` to build a `sort_field` argument ([done here](https://github.com/ualbertalib/jupiter/blob/integration_postmigration/app/services/user_search_service.rb#L32)) that is an array (probably `[:sort_year, :record_created_at]` but should check with Metadata and Sean) to give it a secondary sort criteria that makes sense as a recency fallback when two things have the same sort_year.

**Comment by seanluyk** [comment]
@anayram flagging you on this for a metadata review! I think the original requestor may have been expecting that ERA sorts by "publication year" so that may also explain some of the confusion, notwithstanding the secondary sort issue

**Comment by mbarnett** [comment]
Just to flesh out the details for everyone, `sort_year` is itself an auto-generated piece of data that comes from extracting the year out of "date created" – iirc this extraction was done because of the desire to facet on years. I don't know that sorting by `sort_year` was actually _ever_ a good idea – I think it might be a mistake based on the fact that someone named it `sort_year` instead of `facet_year` and that it subsequently was interpreted as "the thing we should be sorting on" despite it being too imprecise to yield a useful sort order. 

I don't think we actually track a "date published" for all Items & Theses separate from "created" (and since we have some pre-published things like draft articles, those aren't equivalent if I understand correctly?). Looking at it now, we could probably just sort directly on "created" if the data in that field is sufficiently reliable (although the code seems to indicate that it's not reliably parseable as a date, which leads me to think we might have freeform data in there and will need to continue to generate some sort of massaged sort field regardless)

**Comment by anayram** [comment]
Thank you @seanluyk  for looping us in and thanks @mbarnett  for the explanation on how `sort_year` date is used.

Short answer: because the properties `created`(IRItem) and `graduationDate` (IRthesis) contain the actual dates we need to use for sorting (see longer answer regarding `created`) I am proposing two options below. I am leaning to the second one but I'd like to hear @sfarnel and @seanluyk views.

1. to sort by existing `created` and `graduationDate` dates, ignoring non-standard dates (in this case, decisions for sorting non-standard dates would need to be arbitrarily decided on the application side, many objects would be at a disadvantage), or
2. to investigate how extensively non-standard date formats have been used in `created` and derive a normalized field that contains _the most granular date possible_ (for all dates we can at least extract a year).

Longer answer regarding dates of creation vs dates of publication:
I can't comment on the decision to use `dc:created` as property for dates in ERA (I was away when this work was done), but I can confirm that this property captures both dates of creation and dates of publication, whichever is available in resources (I don't know which one users prefer when both are available). Because we are dealing with resources created by local communities mostly, and because most of those resources have not been published before, types of dates reported in those resources vary greatly (and it is often impossible to know which type of date authors or editors are referring to). While we cannot ensure that one or both dates will consistently be available, we need a primary date--especially for citation purposes. Thus, we have a single field that can be used for both types of dates and this is what we need to use for sorting. So I propose the above options unless there is a better idea I haven't thought of.

**Comment by mbarnett** [comment]
Thanks Mariana.

Realistically, because we're at the mercy of the capabilities of Solr for our searching and sorting needs, #2 is functionally the only option, because we can't arbitrarily tell Solr how to deal with non-standard dates in the created field in a satisfactory way (our options on a straight text field like created are effectively just "sort lexicographically", which will produce very strange results for numbers).

Right now we're effectively doing #2 but normalizing to an incredibly un-granular date (just the year), primarily for faceting purposes and then accidentally for sorting. So it sounds like what we want to do here is keep deriving the year for faceting, survey the existing data to develop a set of rules for extracting most-granular dates in cases where things don't have a created like "2016-11-01" (eg. [many published articles](https://era.library.ualberta.ca/search?facets%5Bitem_type_with_status_sim%5D%5B%5D=article_published&search=) just seem to have a year), and then use those rules to derive a second field that acts as a more granular date for sorting?

**Comment by anayram** [comment]
@mbarnett yes, that sounds good to me, and some granularity details can be interpreted easily (e.g. theses' `graduationDate`, where things like "Spring yyyy" or "Fall yyyy" can be normalized to "06/yyyy" or "11/yyyy"

On our side we could help with surveying the data and identifying some rules if that is useful? If I understand well this field would be an auto-generated piece of data like `sort_value` is generated (?), but do let me know if instead we need to provide the normalized values.

**Comment by sfarnel** [comment]
Thanks @mbarnett and @anayram! I think the approach outlined makes good sense and does the best we can with the data we have. (Dates ... always problematic but so essential!)
