### ISSUE TITLE
Add style to facets on Admin Communities page

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#187]
https://github.com/ualbertalib/jupiter/blob/master/app/views/admin/communities/index.html.erb#L59-L74

**Comment by murny** [comment]
Will add mockup for this next week

**Comment by cwant** [comment]
Just to be sure: the admin communities mockup now shows an auto-complete and no faceting. If this is the plan, this ticket should be closed (or it's scope modified to be applicable to auto-complete).

**Comment by murny** [comment]
I;m not sure what the facets would be for communities? They have no fields other then title/description/logo etc? 

But yes, a typeahead that shows two lists matching the query, one for communities and one for collections as user searches.

Maybe someone else can answer facet question regarding this?

**Comment by mbarnett** [comment]
Facets would be presented for the items in it -- ie you could drill down by item facets for items in that community.

May not be a specific req for the Admin UI but is for the general user view of Collections and Communities:

https://docs.google.com/document/d/1tpDL3N6rgE_rQr1X4hPP-wIv4uCcOUINPLIhHu23DTw/edit

> User should be able to facet (with same options as search results pages)

**Comment by mbarnett** [comment]
(I "wrote" this ticket the day I left but I'm pretty sure I mean this more in terms of providing facets for the general Community and Collection UIs and the Admin view was just my quick demo of how to do it)

**Comment by cwant** [comment]
I think there is some confusion about this one. The page lists the communities, and as far as I know won't show items, so faceting would likely be of limited value. I've opened a new ticket for the user community page to match the wireframes, but since the functionality is so similar, it might be work closing this ticket and broadening the scope of the other one to handle both admin/users community page. The other ticket is #229

**Comment by weiweishi** [comment]
According to the wireframe, faceting is required on the collection detail page. This issue is succeeded by #247
