### ISSUE TITLE
Evaluate Web/App servers for production

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#202]
Henry wants to know what we should use for staging/production. There is a heavy cargo cult here to use Apache and Passenger, as this is what we used in ERA (as we were forced to use since shibboleth depends on Apache (and Passenger is the logical choice to use with Apache)) and what the UNIX team is familiar with supporting. 

UAT environment is using Nginx and Puma. Lets do a bit of due diligence and investigate the pros and cons of each? Maybe consolidate UAT and Staging/Production to use the same things?

### Nginx

**Pros**

- Uptrend in market share, [prefferred web server for rails application](http://rails-hosting.com/2016/?__hssc=171373119.1.1508436906892&__hstc=171373119.f4578f0a88b235a76312452abe27fde6.1508436906892.1508436906892.1508436906892.1&__hsfp=763171523&hsCtaTracking=d96c7fe0-5345-440d-895a-fbfb1ff87136%7C4a789563-c98b-4795-9e1d-efe6d815cf1b)
- Lightweight and easy to configure
- Ability to scale easily on minimal hardware
- Support advanced features such as media streaming, reverse proxying for non-http protocols (TCP and email connections)
- Good at dealing with high volume of concurrent accesses
- Great for serving static contents, better performance
- Used by well-known busy sites such as pinterest, reddit, stackoverflow etc. 
- ModSecurity is available for Ngnix, but it requires compilation:https://geekflare.com/install-modsecurity-on-nginx/
- Code base is significantly smaller so the risk of security vulnerability is lower for a forward-thinking security perspective. 

**Cons**
- Something new to us
- Need to reconfigure our ModSecurity module with Nginx and that can be time-consuming. 

### Apache
**Pros**
- Performance is in par with Ngnix when serving dynamic contents
- Has the flexibility with dynamic module loading
- .htaccess configuration at directory level
- Have in-house standard practices developed over the years in term of security
- Still the biggest market share for web servers, proven over many years. 
- Currently, have more third-party support

**Cons**
- downtrend solution in the market
- Big code-base, heavyweight comparing to Nginx. 

**Stack comparing in the wild**
https://stackshare.io/stackups/apache-httpd-vs-microsoft-iis-vs-nginx

### Puma
**Pros**
- Easy to configure as out-of-box. 
- [Preferred app server for Rails](http://rails-hosting.com/2016/?__hssc=171373119.1.1508436906892&__hstc=171373119.f4578f0a88b235a76312452abe27fde6.1508436906892.1508436906892.1508436906892.1&__hsfp=763171523&hsCtaTracking=d96c7fe0-5345-440d-895a-fbfb1ff87136%7C4a789563-c98b-4795-9e1d-efe6d815cf1b). The default app server for Rails 5 apps
- Lower memory usage and response times than Passenger
- is a multi-threaded server, and can handle high-traffic apps. 

**Cons**
- Very new, first showing in 2014. 
- Requires system-level expertise to tune Puma and get the full advantage of Puma as a multi-threaded server

### Passenger
**Pros**
- Well-documented, easy setup and tools to use
- Have the option of paid/more features and support version: Enterprise
- Has the ability to kill off workers that don't have enough traffic to justify their existence to conserve memory and dynamically respawn them as needed
- Works well to host multiple applications on medium sized vms. 
- Sufficient to Jupiter's need

**Cons**
- Single-threaded server

### Comparing Unicorn with Puma and Passenger
- Puma performs better than Unicorn in all tests that were either heavily IO-bound or that interleaved IO and CPU work. In the CPU-bound tests where Unicorn performed (slightly) better than Puma. 
https://deliveroo.engineering/2016/12/21/unicorn-vs-puma-rails-server-benchmarks.html
- Unicorn is susceptible to slow client attacks. 
- Unicorn is not well suited to applications that have long-running requests, large uploads, or long-polling/websockets. 

  | UNICORN | PUMA | PASSENGER 5
-- | -- | -- | --
Clustering | Yes | Yes | Yes
Multithreaded | No | Yes | Enterprise Only
Slow client buffering | No | Yes | Yes
ActionCable | Yes | Yes | Yes
Support | Open Source | Open Source | Open Source / Paid
Installation | Gem | Gem | Binary or Gem
Zero-Downtime Deploys | Yes | Yes | Enterprise

### Recommendation based on: https://www.engineyard.com/blog/ruby-app-server-arena-pt2

Recommended Application Server

Scenarios | App Server 
------------ | -------------
Multiple apps, low traffic, limited hardware | Phusion Passenger
Live Streaming in Rails 4, Long Polling | Thin, Puma (on JRuby or Rubinius for threads)
Single application fast request/response (API for example) | Unicorn

Sources:
http://www.hostingadvice.com/how-to/nginx-vs-apache
https://www.digitalocean.com/community/tutorials/apache-vs-nginx-practical-considerations
https://www.engineyard.com/blog/ruby-app-server-arena-pt1
https://www.engineyard.com/blog/ruby-app-server-arena-pt2
http://www.akitaonrails.com/2016/03/22/is-your-rails-app-ready-for-production
http://blog.scoutapp.com/articles/2017/02/10/which-ruby-app-server-is-right-for-you

**Comment by nmacgreg** [comment]
Cargo cult?  Is that what you think of us?  How rude!

**Comment by murny** [comment]
@nmacgreg Sorry if any offense taking but this wasn't directed at your team, more so our entire organization in general (most definitely our team as well). We choose technologies very poorly here, without any real rationalization other then
- We used it before
- Other people used it before (libraries in general)

"Cargo cult programming can also refer to the results of applying a design pattern or coding style blindly without understanding the reasons behind that design principle"

This issue is to document and put just a bit of thought into this decision (as it is a big architecture decision). Instead of just blindly choosing something because this is what current ERA uses. Or someone is familiar with X, so lets use X.

**Comment by nmacgreg** [comment]
> Maybe consolidate UAT and Staging/Production to use the same things?
Please don't forget to collect requirements from the team that is oncall.

**Comment by murny** [comment]
> Please don't forget to collect requirements from the team that is oncall.

This is why doing your homework and putting some thought into this is important. Absolutely we should collect requirements from all stakeholders (including those oncall who will be supporting this).

**Comment by weiweishi** [comment]
@nmacgreg sorry if this phrase, or this issue and request has offended you and your team. But as @murny  mentioned above, and as I said in my email to Henry, we are not suggesting that we need to change from Apache and Passenger to Nginx and Puma. We don't have a strong opinion against any one. We had to choose Apache because part of our stack relies on it and because it was the most familiar one to our team (which is a legitimate pro if we stay with the stack too!). 

We are just hoping that now we have the freedom to choose a stack that works best for us, we can take some time to evaluate the alternative solutions out there, understand the pros and cons on these popular ones other rails apps choose to use, and make our decision more consciously. And this needs to take into considerations of all the concerns you might have in terms of policy and efforts required to adapt new technology. 

We are also reevaluating Fedora as our object store, whether to get rid of it or to use it only in the preservation DAMS layer, instead of the front end layer driving the application. Even we have had years of experiences with Fedora 3 and 4, we'd like to understand the reason why we need to continue to use this technology if it becomes our bottleneck, and what could be a more standardized/better-performed alternative, if they exist. 

So we are not asking you and your team to switch gears and adopt something new, I simply hope that we can take this opportunity since we are starting fresh, to reevaluate our selections of technology, and see if what we currently use still is the best compromise we need to make, and not become too attach to one solution over the other, just because we decided to use it a few years ago.  

Sorry if our messages or requests are in any way offensive, that has not been our intention. 



Weiwei

**Comment by henryzhang87** [comment]
Puma vs Passenger: Hongli Lai to Evan Phoenix

Based on Hongli's comparison, Passenger Enterprise has obvious edges over Puma. It was written in 2014, and three years passed, not sure what is the current status. 

If comparing Passenger free version with Puma, when the application has a lot of slow I/O, then Puma is better. This requires us to characterize our Jupiter application. Is it CPU intensive or I/O intensive or a mixture of these two?

https://github.com/phusion/passenger/wiki/Puma-vs-Phusion-Passenger

**Comment by henryzhang87** [comment]
**NGINX vs. Apache: Our View of a Decade-Old Question**

Two nice articles talking about Nginx and Apache
1) [NGINX vs. Apache: Our View of a Decade-Old Question](https://www.nginx.com/blog/nginx-vs-apache-our-view/)
2) [NGINX vs. Apache (Pro/Con Review, Uses, & Hosting for Each)](http://www.hostingadvice.com/how-to/nginx-vs-apache/)

The main points
1) Apache is still holding double the market shares vs Nginx, but Nginx is in an uptrend, Apache is in a downtrend
2) Nginx is good at dealing with high volume of concurrent accesses
3) Nginx is 2.5 faster than Apache when serving static contents at 1000 concurrent requests/second
4) Nginx and Apache perform about the same when serving dynamic contents (hosting Php applications)
5) Apache has more flexibility with dynamic module loading,  .htaccess configuration at directory level etc
6) Apache can works under more operating systems, but we use Linux, it doesn't matter much to us
7) Documentation and Support are about the same
8)) Security wise, no obvious advantages. But we do have some standard practices developed by the system administrators and the security staff.

Conclusion:
" High-traffic website owners that need to serve a lot of static content and/or media streams will probably prefer NGINX (or use a combination of Apache and NGINX). In most other website use cases, either web server will do the job just fine." 

So again, this calls for better characterization of our application such as
- is the web page rich and heavy?
- the ratio between static pages/dynamic pages
- the peak concurrent requests

**Comment by cwant** [comment]
Here's an article on Passenger/Puma performance tuning (included with today's Ruby Weekly mail-out) that may (or may not) be interesting to this discussion:

https://www.speedshop.co/2017/10/12/appserver.html

It doesn't really have a bias towards either app server.

**Comment by weiweishi** [comment]
I've summarized my readings and Henry's findings in the ticket. @henryzhang87 could you please review and let me know if I missed any key points. 

And after these readings/investigation, and some discussions with @pbinkley, my senses are:
 - Anyone of these combinations: Apache/Passenger vs Nginx/Passenger or Nginx/Puma can serve our requirement for Jupiter in terms of stability, performance and security.  
 - The performance gain we might get from a different web server/app server stack other than Apache/Passenger probably won't be significant based on the characteristics of our Jupiter application. However, we might be able to see some performance gain for project like Discovery where multithreading could shine after we handle some of the EBSCO API calls by AJAX (and remove that as a bottleneck. 
- Giving the timeline of the Phase 1 of Jupiter, at the time it probably makes sense to set up the stack with Apache/Passenger, just so that we can continue to move along.  
- The smaller code base of Nginx could be a benefit from the security perspective in a long run, so it worth keeping it on our radar. 
- It would really beneficial to set up some performance monitoring for Jupiter such as New Relic to really understand the performance of our stack, and have data/evidence to support any decision we need to make for our stack. 

Any thoughts?

**Comment by weiweishi** [comment]
Decision are made for the timebeing:
we will use Passenger and Apache for web and application server
