### ISSUE TITLE
Upgrade Sidekiq to version 6.x

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#2189]
We currently have sidekiq pinned on v5.X. There appears to be some breaking changes and cleanup to get us on this version.

Should also make sure existing add-on gems like sidekiq-cron and sidekiq-unique-jobs are still working correctly on this new version!

Here's some more info: 
https://github.com/ualbertalib/jupiter/pull/1279

**Comment by pgwillia** [comment]
- [ ] WARN: DEPRECATION WARNING: Initialization autoloaded the constants ApplicationJob, EmbargoExpiryJob, GarbageCollectBlobsJob, and RemoveInactiveDraftsJob.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ApplicationJob, for example,
the expected changes won't be reflected in that stale Class object.

These autoloaded constants have been unloaded.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.
 (called from <top (required)> at /home/pjenkins/Code/ualbertalib/jupiter/config/environment.rb:5)

**Comment by pgwillia** [comment]
- [ ] Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
```
redis.pipelined do
  redis.get("key")
end
```
should be replaced by
```
redis.pipelined do |pipeline|
  pipeline.get("key")
end
```

**Comment by pgwillia** [comment]
- [ ] `Redis.current=` is deprecated and will be removed in 5.0. (called from: jupiter/config/initializers/redis.rb

**Comment by pgwillia** [comment]
- [ ] logging changed

**Comment by pgwillia** [comment]
In production
