### ISSUE TITLE
OAI: change mappings for oai_etdms date values

### ISSUE THREAD

**Issue by anayram** [ualbertalib/jupiter#2298]
**Request**
Change mappings for `oai_etdms` `date`. Instead of using `dc:dateAccepted values`, map from `ual:graduationDate` to meet [LAC requirements](https://www.bac-lac.gc.ca/eng/services/theses/Pages/universities.aspx). This change would meet LAC's requirements (to deliver an _issuance_ date, rather than a _processing_ date, e.g. institutional acceptance date). Additionally, I understand this change would also meet FGSRs preferences but I don't have any details on this.

**Background**
LAC requires "Date on title page" of theses to be captured in `etd-ms:date` OAI elements. Dates in theses' title pages are currently captured in `ual:graduationDate` properties. I understand that FGSR has also expressed a preference in using `ual:graduationDate` as the main date, although I don't have exact details of this conversation.

Currently, our OAI mappings use values from `dc:dateAccepted`. Changing mappings to use `ual:graduationDate` would meet both LAC requirements and FGSR's preferences.

We have updated mappings in metadata documentation files at:
[Jupiter Oai_Etdms Application Profile](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_oai_etdms.md
)
and
[Jupiter OAI mapping](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/Jupiter%20OAI%20mapping.xlsx)

**Context**
From the metadata point of view, this change is crucial before LAC's harvest, but we understand that service and development work priorities will inform work on this request. Thank you!

@sfarnel @ConnorSheremeta

**Comment by jefferya** [comment]
Notes from investigations:

* acts_as_rdfable serializes OAI. Details [here](https://github.com/ualbertalib/acts_as_rdfable/blob/ad213eae97d8166a1a190702f3e0eb9a5014b808/lib/acts_as_rdfable/serializers/oai_etdms.rb#L14)
 ```
      oai.etd_ms(:date, object.date)
```
* `date` defined in the thesis decorators. Details [here](https://github.com/ualbertalib/jupiter/blob/d25903a8e91996ca871bfe3253cd3b23ab52f57a/app/decorators/metadata/oai_etdms/thesis_decorator.rb#L21-L24) 

ToDo:

* investigate options: the stored the graduation date doesn't meet [LAC requirements](https://www.bac-lac.gc.ca/eng/services/theses/Pages/universities.aspx) (i.e., no fall/spring allowed in the string -- Fall 2011 graduation dates)
  * Review code: how is graduation date used elsewhere in the system? Has graduation date format been addressed elsewhere in the codebase? 
  * Otherwise, ask Mariana for advice and example formats for testing.
 
* Implementation considerations: new decorator or reuse existing? Review codebase to see if the `date` decorator can be changed or does this have unintended side-effects and a new decorator should be created instead?

**Comment by anayram** [comment]
@jefferya Spring dates can be entered as 06-YYYY, and fall dates can be entered as 11-YYYY. Hope this helps but let me know if I can help in any another way.

**Comment by pgwillia** [comment]
@jefferya I encountered a similar challenge with the requirements for Extended Date/Time Format in Digitization content.  This is what I ended up introducing: https://github.com/ualbertalib/jupiter/commit/b6cbe7b6ce2d91eb40bd4597dcbdd4aeb07db42d

**Comment by anayram** [comment]
Verified all `etd_ms:date` capture values from `graduation_date` in era-test and era-app-stg-1.
