### ISSUE TITLE
URL Redirect

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#355]
- [ ] Port over the code from HN to Jupiter for Fedora3 uuid redirect

Items deposited in /migrated from HN will maintain their URL/Id structure. No work required. 
Any migrated object would have their handles updated already with the HN url. No redirect needed.

**Comment by pbinkley** [comment]
The pre-HN to HN redirects are here:

https://github.com/ualbertalib/HydraNorth/blob/master/config/routes.rb#L36-L46

```
  # redirect old item url to hydranorth
  get '/public/view/item/:uuid' => 'redirect#item'
  get '/public/view/item/:uuid/:ds' => 'redirect#datastream'
  get '/public/view/item/:uuid/:ds/*file' => 'redirect#datastream', format: false
  get '/public/datastream/get/:uuid/:ds' => 'redirect#datastream'
  get '/public/datastream/get/:uuid/:ds/*file' => 'redirect#datastream', format: false
  get '/public/view/collection/:uuid' => 'redirect#collection'
  get '/public/view/community/:uuid' => 'redirect#collection'
  get '/public/view/author/:username' => 'redirect#author'
  get '/action/submit/init/thesis/:uuid' => 'redirect#thesis'
  get '/downloads/:id' => 'redirect#sufiadownload'
```

They're implemented in the [RedirectController](https://github.com/ualbertalib/HydraNorth/blob/master/app/controllers/redirect_controller.rb).

They are mostly based on the Fedora 3 UUID and the datastream label, and need to be reimplemented in Jupiter to reach the same item-level or file-level target. They should be permanent redirects (301) so that search engines pick up the change without our losing page rank.

The value in maintaining these ancient patterns is to serve users who find links to ERA content in places like old article or thesis PDFs, which will never be updated to point to current locations.

**Comment by pbinkley** [comment]
New redirects from HN to Jupiter:

- [ ] HN ```/files/<noid>``` to Jupiter ```/items/<noid>```
- [ ] HN ```/files/<noid>/<filename>``` to Jupiter ```/items/<noid>/download/<filename>```

These must be implemented as new routes (like above) and new methods in the RedirectController (or wherever those redirects end up being implemented in Jupiter). The item- and file-level methods that implement the pre-HN to HN redirects listed above can be updated to redirect to the Jupiter urls as well, to avoid unnecessary chained redirects. These will all be 301 redirects.

**Comment by pbinkley** [comment]
- [ ] redirect non-existent files to the item level

e.g. ```/files/<noid>/<filename>```, where no such file exists in the Jupiter object, will redirect to ```/items/<noid>```. This may happen when a zipped item in HN is unzipped to reveal individual files in Jupiter (and the zip file is no longer present). In this case, a 302 redirect should be used (since it's possible this could happen due to migration glitches, in which case we'll restore the file) - this will prevent losing page rank unnecessarily. At some point post-migration we can change this to a 301, when we sure we won't do any more restoring.

**Comment by pbinkley** [comment]
- [ ] collection and community urls will require inspection of the object to determine the target, since in HN they have the same form

HN ```/collections/<noid>``` could be a community or a collection. So the target would be ```/communities/<noid>``` or ```/communities/<community noid>/collections/<noid>```, depending on what the object is. Perhaps it's easiest just to maintain a lookup table somewhere of the final list of HN communities and collections for this purpose. The redirects will be 301s.

**Comment by cwant** [comment]
HydraNorth has a Solr index called `ark_id_tesim`. Jupiter doesn't have that ... should it?

**Comment by pbinkley** [comment]
No. 

That harks back to the days when I hoped ARKs would be the basis of our permanent ids. We'll need to look at this again for the digitization phase, but if we're not capturing the shadow ARKs that EZID creates as part of the DOI creation process, then we don't need a Solr index for them. When the digitization requirements are clarified we can always capture the ARKs for existing ERA content then if we need to.

**Comment by cwant** [comment]
I'm not sure how datastream label maps onto something current in Jupiter. A hint or an example would be appreciated.

**Comment by cwant** [comment]
Or is the datastream label just the filename?

**Comment by pbinkley** [comment]
It's just the filename.


Peter Binkley, Ph.D., MLIS / Digital Initiatives Technology Librarian /
peter.binkley@ualberta.ca
2-10K Cameron Library / University of Alberta / Edmonton, Alberta / Canada
T6G 2J8
phone 780-492-3743 / fax 780-492-9243

**Comment by cwant** [comment]
Looking here it seems that there may be another URL route from HydraNorth we need to support:
https://github.com/ualbertalib/HydraNorth/blob/master/app/controllers/redirect_controller.rb#L52

- [ ]￼ HN `/files/<noid>?file=<filename>` to Jupiter `/items/<noid>/download/<filename>`

**Comment by pbinkley** [comment]
I analyzed the existing logs (going back to early December) to detect patterns for redirects for non-bot traffic. The distribution is this:

```
  49562 /downloads/$NOID
  14225 /public/view/item/$UUID/$DS/$FILENAME
  12560 /public/datastream/get/$UUID/$DS
   6443 /public/view/item/$UUID
   3223 /public/view/item/$UUID/
   2937 /public/home
   1284 /public/datastream/get/$UUID/$DS/$FILENAME
    729 /public/view/community/$UUID
    485 /public/view/collection/$UUID
    103 /downloads/$NOID/
     15 /downloads/$NOID?file=thumbnail
(then miscellaneous broken requests)
```

On this basis we can ignore the ```?file=<filename>``` pattern: it only applies to thumbnails and is very very rare. The ```/public/datastream/get/$UUID/$DS``` is common enough to try to handle. I think the best we can do is permanent redirect to the item (```/items/$NOID```), and wait for these to be dropped by the search engines where users are getting the links.

**Comment by cwant** [comment]
The PR is ready for review. @pbinkley might be worth looking over the test cases for a sanity check:

https://github.com/ualbertalib/jupiter/pull/460/files#diff-12ad56f7b71af77dea49007b0d593252R39
