### ISSUE TITLE
left panel of item view too wide with long file names

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#401]
![image](https://user-images.githubusercontent.com/2047614/35462021-84bb57a2-02a7-11e8-8781-bd0b06e4026d.png)

The left panel should be contained in a certain size and wrap the filenames or collection/community path as needed.

**Comment by cwant** [comment]
Did you mean 'left side'?

**Comment by murny** [comment]
We should be using bootstraps grid system here (col/rows) instead of flexbox. Gives better predictability. Plus current solution doesn't work on mobile either.

**Comment by cwant** [comment]
Below is screenshot with `col-4` for files/paths and `col-8` for main content. I had to introduce inter-word wrapping so that text didn't overflow (other option is truncate it with ellipses, and maybe providing full name on hover). As a result of the wrapping, the view and download links needed to be moved to a different line to look sane.

Works for you guys?

![files-to-col](https://user-images.githubusercontent.com/672104/35578009-2888cd74-05a0-11e8-9faf-436061c507bf.png)
