### ISSUE TITLE
Admin Block User Functionality

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#41]
DONE WHEN:

- [ ] blocked column on user model
- [ ] add informational block page (contents?)
- [ ] if blocked is true on user login, all routes redirect user to blocked page

**Comment by murny** [comment]
This is done in https://github.com/ualbertalib/jupiter/pull/56. However we decided to change the name of `blocked` to something more user friendly as `suspended`.

Also did not implement a "block page" as noted above. Instead when a user tries to login after being suspended, they will simply be given the following flash message:
 ```
user_suspended: 'Sorry, your account has been suspended. If you believe this is an error, please contact a staff member.'
```
Or if an admin suspends a user while the user is still logged in, the next time they go to a new page, they will be logged out and given the same flash message above.

As chris noted in the PR, it be nice to be able to give a reason why a user was suspened. This is helpful for both internal purposes (aka why did leah banned this user?) and also for external purposes, so a user knows why they were banned. This would involving adding a bit more effort to complete (string column on user model, probably instead of a confirm dialog, you would have a modal which you can put in the reason why they are being banned, then having this message being displayed on admin user show page and user suspended flash message)

**Comment by leahvanderjagt** [comment]
Blocking is extremely rare so I am OK with a more generic message. I would
just amend the message to read:

Sorry, your ERA account has been suspended. Please contact the ERA
HelpDesk at erahelp@ualberta.ca for more information.


___________________________________________________________




*Leah VanderjagtDigital Repository Services Coordinator University of
Albertat. 780.492.3851 *
*leahv@ualberta.ca <leahv@ualberta.ca> *

**Comment by murny** [comment]
Updated message accordingly. Thanks @leahvanderjagt
