### ISSUE TITLE
file download URL under fileset id

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#434]
A URL for viewing a fileset looks like this: `http://localhost:3000/items/e5ec5a21-84d9-41e8-8a91-883580a7a265/view/huh.jpeg`.
The issue is that the id that appears after `item` is the fileset id not the item id.

We will need to fix the url so that file download sits below the metadata page, with item id. This is one of the requirements from Google Scholar.

**Comment by pbinkley** [comment]
Summary of discussion on Slack, Feb. 6, raising issues which on further investigation might prompt us to change our url patterns:

- to handle the possibility of duplicate file names within an item (e.g. if a researcher uploads a file named "results.csv" from each of several directories), we'll include the fileset id in the download and view urls, before the file name. This is in line with decisions made about the structure of the lightweight AIP to deal with the same possibility.
- I raised concerns about the two links (view and download) to the same target (e.g. the pdf of a thesis), and whether this would affect Google's handling of our site. I think my anxiety can be put to rest simply by adding no-follow to the view link so that Google will only see the download link; we also decided to drop the file name from the view link, so that the download link would be the preferred option for Google Scholar (which wants to see a '.pdf' at the end of the url).
- I raised the question of whether the view and download links will reliably behave differently (and not just follow the user's preferences as configured in the browser). I've tested a little further with UAT and yes, they do behave as intended, so I'll drop this concern, and drop the suggestion I based on it to simplify the download/view urls by removing the verb.

The proposed changes to previous decisions are therefore:

- [ ] add the fileset id to the download and view urls in order to prevent problems from duplicate file names within an item
- [ ] add no-follow and remove the file name from view urls in order to direct Google's attention to the download url

**Comment by cwant** [comment]
The download url returns a forced mime type of 'application/octet-stream' to ensure that a download dialog opens in most browsers, so I wonder if google's attentions should be directed to the view url instead?

**Comment by pbinkley** [comment]
Good point. In that case we would restore the file name on the view link (so Google Scholar is happy) and move the no-follow from view to download. With the no-follow in place there's no particular need to remove the file name. Any objection?

**Comment by johnhuck** [comment]
It sounds to me like we're all on the same page here, so this comment is more just informational for our convenience. I went back to find the particular instruction in the Google Scholar inclusion guidelines that is at play here. For our reference, here it is. It's actually a point made under the guidelines for the meta tags. Under 2H:

The "<meta>" tags normally apply only to the exact page on which they're provided. If this page shows only the abstract of the paper and you have the full text in a separate file, e.g., in the PDF format, please specify the locations of all full text versions using citation_pdf_url or DC.identifier tags. **The content of the tag is the absolute URL of the PDF file; for security reasons, it must refer to a file in the same subdirectory as the HTML abstract.**

https://scholar.google.ca/intl/en/scholar/inclusion.html#indexing

**Comment by johnhuck** [comment]
So the landing page and the pdf have to be in the same directory. That's my interpretation. Not sure that's quite the same as having the .pdf file sit under the metadata page, but I will leave it to you to make the final determination about what that means for us.
