### ISSUE TITLE
Admin needs to be able to delete items

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#468]
We currently show a "Delete" button on each item on the list views (search/users profile/collection index/etc). However currently this isn't wired up.

- Need to add a delete action to Admin::ItemsController and handle the deleting of items appropriately 

Duplicate issue here #579 from sfbetz:

> Trying to delete test items leads to a 404 error.
> 
> Logged in to my sfbetz user account - trying to delete this item:
> https://era-beta.library.ualberta.ca/items/06ec0895-075d-4098-80c9-ebb1795db937
> 
> Delete fails whether I try it from delete button on a search results page like this: https://era-beta.library.ualberta.ca/search?search=lorem+ipsum
> 
> Or from user account page like this: https://era-beta.library.ualberta.ca/admin/users/877
> 
> Error message:
> 
> This era-beta.library.ualberta.ca page can’t be found
> No webpage was found for the web address: https://era-beta.library.ualberta.ca/items/06ec0895-075d-4098-80c9-ebb1795db937
> HTTP ERROR 404
> 
> I am able to successfully delete "draft" files with no issues.

**Comment by mbarnett** [comment]
@sfbetz should this include Theses, or strictly Items?

**Comment by mbarnett** [comment]
When you call destroy on the item, it should kick off a job to tombstone the DOI automatically, so that part is done.

You'll want to delete the activestorage blobs and and doi_state records _after_ the object is deleted. Normally there would be a dependent delete on the join table, but because the object lives in Fedora and the dependent records live in Postgres, you'll need to do it manually in an after_destroy hook.

**Comment by weiweishi** [comment]
@weiweishi will verify if DOI is actually tombstoned. and if that's case this ticket can be closed
