### ISSUE TITLE
Last step of deposit needs some progress/action indicator

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/jupiter#580]
During deposit, there can be some wait time one the last step while file is processing. It's long enough to look to a user like the page is frozen / broken, especially if they don't see the spinning wheel on the browser tab. We need some way to indicate that there's something happening behind the scenes (message, animation, other?).

**Comment by pgwillia** [comment]
I think there are a few approaches to the problem:
1. Redirect the user to another page quickly with a message that their request is being processed.
 * make the review_and_deposit_item an [ActiveJob ](http://guides.rubyonrails.org/active_job_basics.html) to run in the background
 * no javascript involved
 * currently the wait is for the item that the user is creating to be created and stored to Fedora so that it's page can be displayed
2. Wait for the page but [display something](http://www.codemag.com/article/1507051/Display-a-Progress-Message-on-an-MVC-Page)
  * Disable all the buttons on the screen so they can’t click anything else.
  * Hide all of the buttons on the screen so they can’t click any of them.
  * Change the text on the button they just clicked on.
  * Disable the button they just clicked on.
  * Pop-up a message over the screen.
  * Gray out the page they’re on.
  * Any combination of the above items.
  * is javascript so needs to fail intelligently and all user's won't benefit
3. Use [Turbolinks suggestion](https://github.com/turbolinks/turbolinks#redirecting-after-a-form-submission) to use [XHR submission](http://guides.rubyonrails.org/working_with_javascript_in_rails.html#remote-elements)
 * see also [here](https://github.com/turbolinks/turbolinks/issues/85#issuecomment-338784510)
 * currently uses [simple_form_for which seems to be incompatible with form_with](https://github.com/plataformatec/simple_form/issues/1494) that Turbolinks likes => might be significant rewrite of draft-submission
 * is javascript so needs to fail intelligently and all user's won't benefit

In related news, I learned that [turbolinks ](https://github.com/turbolinks/turbolinks#displaying-progress) provides [a progress bar](http://www.usabilitypost.com/2013/08/19/new-ui-pattern-website-loading-bars/) by default for any page that takes longer than 500ms (.5 seconds) to load. We can style it and also choose the minimum interval before it's shown. Unfortunately Turbolinks doesn't apply to this case (HTTP POST).

**Comment by murny** [comment]
I say you can do something like #2. 

Basically when you submit the form, the button text changes to say 
"<Loading Symbol> Saving Draft..." and the button is disabled.

Basically will just be a simple change on the butotn_tag, no extra javascript needed etc. You can add a data attr called `:disable_with ` which does this all for you. More info here:

`- Value of this parameter will be used as the value for a disabled version of the submit button when the form is submitted. This feature is provided by the unobtrusive JavaScript driver.`

http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/FormTagHelper.html#method-i-button_tag

Also here is an old video tutorial but still relevant: https://gorails.com/episodes/button-loading-animations-with-jquery-ujs

**Comment by pgwillia** [comment]
:100: That works like a treat and small change too! Thanks @murny

**Comment by pgwillia** [comment]
![screenshot from 2018-04-05 13-22-27](https://user-images.githubusercontent.com/1220762/38387398-e023429a-38d4-11e8-8c18-ed6d8bd39ca1.png)
![screenshot from 2018-04-05 13-24-06](https://user-images.githubusercontent.com/1220762/38387399-e04ede32-38d4-11e8-92a3-dab42121c657.png)
@sfbetz How does that look?

**Comment by sfbetz** [comment]
Perfect! I'm assuming the little wheel is animated? Let's change the text to "Saving" to cover scenarios where the user is updating an existing item or uploading a new item. Thanks both!

**Comment by pgwillia** [comment]
closed by #617
