### ISSUE TITLE
Add tests for Controllers

### ISSUE THREAD

**Issue by murny** [ualbertalib/jupiter#865]
Some of our controllers are missing tests (DownloadsController and ItemsController are probably the two biggest but there is a bunch of others here (profiles/robots/static pages/etc))

We should be testing these actions and verifying they are coming back with the proper responses (in DownloadsController case, are the proper disposition and content_type headers set properly?).

**Comment by ConnorSheremeta** [comment]
It appears as though DownloadsController [has had tests added already](https://github.com/ualbertalib/jupiter/blob/master/test/controllers/downloads_controller_test.rb) (although simplecov is still showing 0% coverage for downloads_controller.rb for some reason.) Would it be safe to assume that this issue can be closed?

**Comment by pgwillia** [comment]
Yeah, looks like the tests for downloads controller were added the day after the issue was created. https://github.com/ualbertalib/jupiter/pull/866/commits/2b814d4a8410b82e3bd203f82528b17de304735f

In coverage they're not getting credit?
![Screenshot from 2019-04-12 13-10-46](https://user-images.githubusercontent.com/1220762/56060546-6834b000-5d24-11e9-95a2-f74987aa30bd.png)
  Maybe because of the route changing the name?
https://github.com/ualbertalib/jupiter/blob/4a90d1c4108acc20ca5e6c34e6e1cb38d04dfb1f/config/routes.rb#L24-L25


There are still improvements needed for this and others
![Screenshot from 2019-04-12 13-05-50](https://user-images.githubusercontent.com/1220762/56060327-c1501400-5d23-11e9-8a17-498341b057e8.png)
