### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/jupiter#98]
TODO

Mockup:
![Image of User Dashboard Mockup](https://jupiter.mybalsamiq.com/mockups/6133961.png)
https://jupiter.mybalsamiq.com/projects/jupiter/User%20Dashboard

**Comment by cwant** [comment]
No breadcrumbs on this page? Would it be worth adding a `Home > My Profile` at the top?

**Comment by murny** [comment]
We decided to not have breadcrumbs for a single level deep pages (as it's kinda silly, since the Home link and ERA/Home in the navbar will be right next to each other). 

So none of the pages in the mockups that are single level deep will have breadcrumbs (admin pages like `/admin/users` etc or `/browse` etc). But very nested resources will most definitely have them (/communities/fake-uuid-123/collections/fake-uuid-123/ etc)
