### ISSUE TITLE
[Jupiter] Image collection missing thumbnails for tif files. 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#991]
**Is your feature request related to a problem? Please describe.**
It seems that most image files in this big image collection
https://era.library.ualberta.ca/communities/017b5983-6bca-47d1-9760-0435ed3aedd8/collections/bcf586ac-ab61-49e1-839f-b9f517839e9e don't have thumbnails. 
They are tif files (instead of tiff files). This is an important image collection in ERA and it would be critical to have the thumbnails for items in this collection

**Describe the solution you'd like**
Review the settings in minimagick to ensure tif files can be processed?

**Comment by weiweishi** [comment]
Wasn't able to identify a tiff file within this collection. Let's start with looking into the extensions that minimagick is handling.

**Comment by ConnorSheremeta** [comment]
Looks like .tif files are getting an 'ActiveStorage::InvariableError' when the .variant() method is called on the file which is causing .preview() to be called on the file which gives an 'ActiveStorage::UnpreviewableError' and then the view ultimately ends up just rendering a generic file icon (one partial where this happens is [here](https://github.com/ualbertalib/jupiter/blob/master/app/views/items/draft/_thumbnail.html.erb).)

This looks to be an ActiveStorage issue which [appears to be fixed in rails 6.x](https://github.com/rails/rails/pull/34824) (haven't been able test however and Rails 6 is still in beta). Not sure if it's worth just waiting for a rails 6 upgrade...

It would be possible to use url_for(file) as the first parameter in image_tag just for tifs and then use css to make it the proper size but then you're pulling the full image each time you load a thumbnail instead of just a 100x100 image.

**Comment by ConnorSheremeta** [comment]
```
config.active_storage.variable_content_types.push 'image/tiff'
config.active_storage.content_types_allowed_inline.push 'image/tiff'
```
Can be added to config/application.rb which resolves the issue. It could be removed when we upgrade rails

**Comment by weiweishi** [comment]
Thanks @ConnorSheremeta Work well done. Issue solved in production.
